version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: icecat_postgres
    environment:
      POSTGRES_USER: icecat
      POSTGRES_PASSWORD: icecat
      POSTGRES_DB: icecat_hub
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icecat -d icecat_hub"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
