version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: icecat
      POSTGRES_PASSWORD: icecat
      POSTGRES_DB: icecat_hub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgres://icecat:icecat@postgres:5432/icecat_hub
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: b5ba75b69461bb0017ebea0fde80af6d20656fcd3438c8686795a28a437e17e3
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
volumes:
  pgdata:

